name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '10 5 * * 0'

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js latest
        uses: actions/setup-node@v5
        with:
          cache: npm

      - name: npm install
        run: npm ci

      - name: eslint
        run: npm run lint

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          tools: linked
          languages: javascript, actions
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3


  test:
    name: Test NodeJS ${{ matrix.node.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node:
          - version: 20
          - version: 22
          - version: 24
            options: --test-coverage-lines=100
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node.version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: npm install and test
        run: npm cit
        env:
          CI: true
          NODE_OPTIONS: ${{ matrix.node.options }}
