name: Publish Version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Type of version update to tag
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch
          - Custom
      version-str:
        description: Custom version string (if tagging custom)
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: npm install and test
        run: npm cit
        env:
          CI: true

      - name: npm version
        run: |
            npm version ${{ github.event.inputs.version-type == 'Custom' && github.event.inputs.version-str || github.event.inputs.version-type }}

      - name: git push
        run: |
            git push origin --follow-tags

      - name: npm publish
        run: |
            npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
